### PR TITLE
Adding the blog post from blogs.windows.com to the GitHub readme.

### PR DESCRIPTION
**Pull request by EricAtMSFT**
New Job Title = SnapGold Chief Marketing Officer

### CODE REVIEW

**Comment by AstumppMSFT** [comment]
Looking good.

**Comment by RoeKale** [comment]
Looks good, Chief. Do you want to move the link higher (at the start of the README)?

**Comment by EricAtMSFT** [comment]
I could, Andy, thoughts?

**Comment by AstumppMSFT** [comment]
I think it's quite good where it is positioned right now. We probably want to give the instructions first, then redirecting users to external content.

**Comment by RoeKale** [comment]
Or at least above the picture, like in the blog post.
Keeping it below, could cause it to be ignored.

**Comment by EricAtMSFT** [comment]
Leaving as is. Probably best to focus on what it is first.

**Pull request merged**
